### PR TITLE
Add support for Debian 9.13

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request:
* Pulls in upstream changes
* Fixes broken builds by adding a `prepare.yml` playbook that updates the apt cache for Debian-based OSs
* Adds support for Debian 9.13

## 💭 Motivation and Context

Broken builds must be fixed, and Debian 9 must be supported until CyHy is transitioned to python 3.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
@mcdonnnj I didn't start from your branch since it's easier for me to inspect the changes from the upstream merge if I perform the merge locally.

**Review by mcdonnnj — APPROVED** [review]
Works for me 👍 Thanks for taking care of this fix.

**Comment by mcdonnnj** [comment]
I saw this same behavior when I re-ran the [last passing test in cisagov/ansible-role-kali](https://github.com/cisagov/ansible-role-kali/runs/901371294), so we may want to backport the `prepare.yml` addition to the skeleton.

**Review by dav3r — APPROVED** [review]
Hats off! 🎩

**Comment by jsf9k** [comment]
> I saw this same behavior when I re-ran the [last passing test in cisagov/ansible-role-kali](https://github.com/cisagov/ansible-role-kali/runs/901371294), so we may want to backport the `prepare.yml` addition to the skeleton.

[The update playbook](https://github.com/cisagov/ansible-role-bloodhound/pull/7) if added to [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role) would also fix this issue.  I will create that PR tonight or tomorrow and we can release the Kraken.

**Pull request merged**
